# Generated by Django 4.1.2 on 2022-10-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_language_bookinstance_borrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
